### ISSUE TITLE
Redirect to Login Landing Page

### ISSUE THREAD

**Issue by JPGlaser** [intoxstudio/restrict-user-access#13]
Hello,

First off, I wanted to say thank you for developing such a simple, but extremely effective addition for WordPress. It seems to be working just fine on the install I have it implemented on.

My inquiry lies with the redirect option: Is there a way to have the redirected page be the log-in page or a landing page which says you can’t access this content and asks you to login (if it detects that you are not signed in)? In addition, is there a way to simplify the redirected URL (EX: attempted_page/?redirect_to=https%3A%2F%2Fwww.domain.com/landing_page/)?

Warm Regards,
Joe G.

**Comment by intoxstudio** [comment]
Sorry for not replying to this earlier. In version 0.17 you can redirect to both pages and custom links.

If you only want text to be displayed to users not logged in, create an access level, sync it with Not logged-in users, and use the shortcode` [restrict level="level-name"][text here[/restrict]`

Simplifying the redirection URL could be done by storing it in a cookie or POST (instead of GET). Is this wanted only for atheistic, or does the redirect_to paremeter break anything?
